<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[STEP1]]>
    </line>
    <line>
      <![CDATA[STEP2]]>
    </line>
    <line>
      <![CDATA[STEP3]]>
    </line>
    <line>
      <![CDATA[STEP4]]>
    </line>
    <line>
      <![CDATA[STEP5]]>
    </line>
    <line>
      <![CDATA[STEP6]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="16672" started-at="2018-12-17T12:41:59Z" finished-at="2018-12-17T12:42:16Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="16672" started-at="2018-12-17T12:41:59Z" finished-at="2018-12-17T12:42:16Z">
      <class name="testcases.LoginValidation">
        <test-method status="PASS" signature="prerequisites()[pri:0, instance:testcases.LoginValidation@167fdd33]" name="prerequisites" is-config="true" duration-ms="8657" started-at="2018-12-17T12:41:59Z" finished-at="2018-12-17T12:42:08Z">
          <reporter-output>
            <line>
              <![CDATA[STEP1]]>
            </line>
            <line>
              <![CDATA[STEP2]]>
            </line>
          </reporter-output>
        </test-method> <!-- prerequisites -->
        <test-method status="FAIL" signature="testLoginWithValidData()[pri:0, instance:testcases.LoginValidation@167fdd33]" name="testLoginWithValidData" duration-ms="7978" started-at="2018-12-17T12:42:08Z" finished-at="2018-12-17T12:42:16Z">
          <exception class="atu.testng.reports.exceptions.ATUReporterStepFailedException">
            <full-stacktrace>
              <![CDATA[[ATU Custom Reporter Step Failed Exception]
at atu.testng.reports.listeners.ATUReportsListener.onTestSuccess(Unknown Source)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:70)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- atu.testng.reports.exceptions.ATUReporterStepFailedException -->
          <reporter-output>
            <line>
              <![CDATA[STEP3]]>
            </line>
            <line>
              <![CDATA[STEP4]]>
            </line>
            <line>
              <![CDATA[STEP5]]>
            </line>
            <line>
              <![CDATA[STEP6]]>
            </line>
          </reporter-output>
        </test-method> <!-- testLoginWithValidData -->
      </class> <!-- testcases.LoginValidation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
